import esbuild from "esbuild";
import process from "process";
import fs from "fs";
import builtins from "builtin-modules";

// Two three.js copies in the bundle break rendering at runtime (version-mixed
// scene objects). Fail the build if npm ever un-dedupes three again.
const nestedThree = fs
  .readdirSync("node_modules")
  .filter((d) => !d.startsWith("."))
  .flatMap((d) => {
    const nested = `node_modules/${d}/node_modules/three`;
    return fs.existsSync(nested) ? [nested] : [];
  });
if (nestedThree.length > 0) {
  console.error(
    `Duplicate three.js copies found: ${nestedThree.join(", ")}\n` +
      "Align the top-level \"three\" version with what these packages require, then reinstall."
  );
  process.exit(1);
}

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, visit the plugin's GitHub repository
*/
`;

const prod = process.argv[2] === "production";

const context = await esbuild.context({
  banner: { js: banner },
  entryPoints: ["src/main.ts"],
  bundle: true,
  external: [
    "obsidian",
    "electron",
    "@codemirror/autocomplete",
    "@codemirror/collab",
    "@codemirror/commands",
    "@codemirror/language",
    "@codemirror/lint",
    "@codemirror/search",
    "@codemirror/state",
    "@codemirror/view",
    "@lezer/common",
    "@lezer/highlight",
    "@lezer/lr",
    ...builtins,
  ],
  format: "cjs",
  target: "es2018",
  logLevel: "info",
  sourcemap: prod ? false : "inline",
  treeShaking: true,
  outfile: "main.js",
  minify: prod,
});

if (prod) {
  await context.rebuild();
  process.exit(0);
} else {
  await context.watch();
}
